#ifndef ROBOT_TOY_SIMULATOR_LIB_GLOBAL_H
#define ROBOT_TOY_SIMULATOR_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROBOT_TOY_SIMULATOR_LIB_LIBRARY)
#  define ROBOT_TOY_SIMULATOR_LIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ROBOT_TOY_SIMULATOR_LIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ROBOT_TOY_SIMULATOR_LIB_GLOBAL_H
